<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="../MyUsbIP.Abstractions/MyUsbIP.Abstractions.csproj" />
    <ProjectReference Include="../MyUsbIP.Protocol/MyUsbIP.Protocol.csproj" />
    <ProjectReference Include="../MyUsbIP.NativeServer/MyUsbIP.NativeServer.csproj" />
  </ItemGroup>
</Project>
