<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <AssemblyName>myusbipd</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../src/MyUsbIP.Abstractions/MyUsbIP.Abstractions.csproj" />
    <ProjectReference Include="../../src/MyUsbIP.Server/MyUsbIP.Server.csproj" />
    <ProjectReference Include="../../src/MyUsbIP.Client/MyUsbIP.Client.csproj" />
    <ProjectReference Include="../../src/MyUsbIP.Platform/MyUsbIP.Platform.csproj" />
    <ProjectReference Include="../../src/MyUsbIP.Runtime/MyUsbIP.Runtime.csproj" />
    <ProjectReference Include="../../src/MyUsbIP.NativeServer/MyUsbIP.NativeServer.csproj" />
    <ProjectReference Include="../../src/MyUsbIP.WindowsNative/MyUsbIP.WindowsNative.csproj" />
    <ProjectReference Include="../../src/MyUsbIP.UsbDk/MyUsbIP.UsbDk.csproj" />
  </ItemGroup>
  <ItemGroup>
    <None Update="appsettings.json"><CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory></None>
  </ItemGroup>
</Project>
