<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <InternalsVisibleTo Include="MyUsbIP.SmokeTests" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../MyUsbIP.Abstractions/MyUsbIP.Abstractions.csproj" />
    <ProjectReference Include="../MyUsbIP.Protocol/MyUsbIP.Protocol.csproj" />
  </ItemGroup>
</Project>
