#pragma once

#include <ntddk.h>

#define MYUSBIP_API_VERSION 0x00010000UL
#define FILE_DEVICE_MYUSBIP FILE_DEVICE_UNKNOWN

#define IOCTL_MYUSBIP_EXPORTER_GET_VERSION   CTL_CODE(FILE_DEVICE_MYUSBIP, 0x800, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_MYUSBIP_EXPORTER_LIST_DEVICES  CTL_CODE(FILE_DEVICE_MYUSBIP, 0x801, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_MYUSBIP_EXPORTER_SHARE         CTL_CODE(FILE_DEVICE_MYUSBIP, 0x802, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_MYUSBIP_EXPORTER_UNSHARE       CTL_CODE(FILE_DEVICE_MYUSBIP, 0x803, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_MYUSBIP_EXPORTER_SUBMIT_URB    CTL_CODE(FILE_DEVICE_MYUSBIP, 0x804, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_MYUSBIP_EXPORTER_CANCEL_URB    CTL_CODE(FILE_DEVICE_MYUSBIP, 0x805, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_MYUSBIP_EXPORTER_GET_COMPLETION CTL_CODE(FILE_DEVICE_MYUSBIP, 0x806, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define IOCTL_MYUSBIP_VHCI_GET_VERSION       CTL_CODE(FILE_DEVICE_MYUSBIP, 0x900, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_MYUSBIP_VHCI_CREATE_PORT       CTL_CODE(FILE_DEVICE_MYUSBIP, 0x901, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_MYUSBIP_VHCI_REMOVE_PORT       CTL_CODE(FILE_DEVICE_MYUSBIP, 0x902, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_MYUSBIP_VHCI_GET_PENDING_URB   CTL_CODE(FILE_DEVICE_MYUSBIP, 0x903, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_MYUSBIP_VHCI_COMPLETE_URB      CTL_CODE(FILE_DEVICE_MYUSBIP, 0x904, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_MYUSBIP_VHCI_RESET_PORT        CTL_CODE(FILE_DEVICE_MYUSBIP, 0x905, METHOD_BUFFERED, FILE_ANY_ACCESS)

#pragma pack(push, 1)

typedef struct _MYUSBIP_BUSID_REQUEST {
    ULONG ApiVersion;
    UCHAR BusId[60];
} MYUSBIP_BUSID_REQUEST, *PMYUSBIP_BUSID_REQUEST;

typedef struct _MYUSBIP_DEVICE_RECORD {
    UCHAR BusId[64];
    UCHAR InstanceId[128];
    USHORT VendorId;
    USHORT ProductId;
    ULONG Flags;
    UCHAR Reserved[56];
} MYUSBIP_DEVICE_RECORD, *PMYUSBIP_DEVICE_RECORD;

typedef struct _MYUSBIP_DEVICE_LIST_HEADER {
    ULONG ApiVersion;
    ULONG Count;
} MYUSBIP_DEVICE_LIST_HEADER, *PMYUSBIP_DEVICE_LIST_HEADER;

typedef enum _MYUSBIP_URB_DIRECTION {
    MyUsbIpDirectionOut = 0,
    MyUsbIpDirectionIn = 1
} MYUSBIP_URB_DIRECTION;

typedef struct _MYUSBIP_URB_REQUEST {
    ULONG ApiVersion;
    ULONG Sequence;
    ULONG DeviceId;
    ULONG Endpoint;
    ULONG Direction;
    ULONG TransferFlags;
    LONG TransferLength;
    LONG Interval;
    UCHAR SetupPacket[8];
    ULONG PayloadLength;
    UCHAR Payload[1];
} MYUSBIP_URB_REQUEST, *PMYUSBIP_URB_REQUEST;

typedef struct _MYUSBIP_URB_COMPLETION {
    ULONG ApiVersion;
    ULONG Sequence;
    LONG Status;
    LONG ActualLength;
    ULONG ErrorCount;
    ULONG PayloadLength;
    UCHAR Payload[1];
} MYUSBIP_URB_COMPLETION, *PMYUSBIP_URB_COMPLETION;

typedef struct _MYUSBIP_VHCI_CREATE_PORT_REQUEST {
    ULONG ApiVersion;
    ULONG DeviceId;
    USHORT VendorId;
    USHORT ProductId;
    UCHAR BusId[64];
} MYUSBIP_VHCI_CREATE_PORT_REQUEST, *PMYUSBIP_VHCI_CREATE_PORT_REQUEST;

typedef struct _MYUSBIP_VHCI_CREATE_PORT_RESPONSE {
    ULONG ApiVersion;
    ULONG Port;
} MYUSBIP_VHCI_CREATE_PORT_RESPONSE, *PMYUSBIP_VHCI_CREATE_PORT_RESPONSE;

#pragma pack(pop)
